#!/usr/bin/env python3
"""Compile the YAML model into web/model.json for the browser explorer.

The YAML files in data_sources/ are the single source of truth. The interactive
map (web/explore.html) can't parse YAML, so this script flattens what it needs
into one JSON file. Run it whenever you edit the model:

    python tools/build_model_json.py

CI could run this too; for now we commit the output so GitHub Pages serves it
with zero build step. Editing a threshold in layers.yaml + re-running this is the
whole "add a touch of your own" loop for the visualization.
"""

from __future__ import annotations

import json
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data_sources"
OUT = ROOT / "web" / "model.json"


def _read(name: str) -> dict:
    with (DATA / name).open(encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def main() -> None:
    reg = _read("registry.yaml")
    lay = _read("layers.yaml")

    # Trim sources to what the UI shows (which datasets answer a given layer).
    sources = {
        s["id"]: {
            "id": s["id"],
            "name": s["name"],
            "category": s["category"],
            "layers": s.get("layers", []),
            "auth": s.get("access", {}).get("auth", "none"),
            "docs_url": s.get("docs_url", ""),
            "relevance": s.get("relevance_78738", ""),
        }
        for s in reg.get("sources", [])
    }

    model = {
        "meta": reg.get("meta", {}),
        "sources": sources,
        "layers": lay.get("layers", {}),
        "land_uses": lay.get("land_uses", {}),
        "actor_uses": lay.get("actor_uses", {}),
        "enabling_edges": lay.get("enabling_edges", []),
        "stakeholders": lay.get("stakeholders", {}),
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(model, indent=2)
    OUT.write_text(payload, encoding="utf-8")

    # Also emit a JS global so the explorer works even when opened from file://
    # (browsers block fetch() of local files; a <script> tag is always allowed).
    js = OUT.with_suffix(".js")
    js.write_text(
        "// AUTO-GENERATED by tools/build_model_json.py — do not edit by hand.\n"
        "// Edit data_sources/*.yaml then re-run the build.\n"
        f"window.SIMY_MODEL = {payload};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.relative_to(ROOT)} and {js.relative_to(ROOT)} "
          f"({len(model['land_uses'])} land uses, {len(sources)} sources)")


if __name__ == "__main__":
    main()
